# Introduction

The Project Big Life Planning Tool was developed in order to support health professionals: research, plan, develop, and evaluate evidence-based health interventions.

For instance Project Big Life Planning Tool helps:

- Public health professionals: assess the impact of interventions that target health behaviours
- Health planners: assess the need for palliative care (_To be developed_)

**What types of questions can it answer?**

The Project Big Life Planning Tool can answer the following types of questions: 

- What is the burden of smoking on life expectancy?
- How many deaths would be prevented if everyone increased thier daily exercise by 10%?

**How does it work?**

- This tool provides health planners with access to multivariable predictive risk algorithms, created and housed by the Project Big Life Team.

- The multivariable predictive risk algorithms use distinct characteristics and health profiles of groups of people to assess the risk of a health outcome (e.g. deaths).

- The multivariable predictive risk algorithms are developed and validated using data routinely collected by Statistics Canada and provincial health agencies, and the algorithms have been published in various journals.

- More information about multivariable predictive risk algorithms can be found in the [key concepts](#keyconcepts) or [appendices](#mport).

**Why should I used it?**

- It is **easy** and **flexible** to use. 

    - The user only needs to upload their data and choose which calculation to run.
    - It can be used to assess the future risk of a health outcome.
    - It can be used to assess the effectiveness of different intervention scenarios (e.g. policy) on a health outcome.
    
    
-	It generates **accurate** predictions.

    - It can be used to accurately assess the risk of a health outcome in populations that were not used in its developement, and groups of people that account for only a fraction of the population. 

    
-	It is **private**. 

    - Loaded data remains on your computer and is not uploaded or sent anywhere.


